#!/bin/sh

#skip merge commits
if grep "merge" "$1"; then
    exit 0
fi

current_branch="$(git rev-parse --abbrev-ref HEAD)"
prefix="feature/"
branch_without_prefix=${current_branch#"$prefix"}

echo current_branch

jira_issue_regex="^[a-zA-Z]{2,10}-[0-9]+"
current_issue="$(echo "${branch_without_prefix}" | grep "${jira_issue_regex}" -Eo)"
issue_in_message="$(grep "${jira_issue_regex}" "${1}" -Eo)"

#to uppercase
# shellcheck disable=SC2018
# shellcheck disable=SC2019
current_issue=$(echo "$current_issue" | tr 'a-z' 'A-Z')

# allow if not on feature branch
if [ -z "$current_issue" ]; then
    echo "Don't know current issue"
    exit 0
fi

# add issue to commit message and allow commit if issue is missed in commit message
# "git commit -m test" will produce:
#  [MOBILE-113] test
#  Jira ticket MOBILE-113
if [ -z "$issue_in_message" ]; then
	echo "Add issue $current_issue info to commit"
    # shellcheck disable=SC2028
    echo "[$current_issue] $(cat "${1}") @ Issue $current_issue" > "${1}"
    exit 0
fi