/*
 * Copyright 2023 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.linguistic

internal object LanguageTerritory {
  private val languageTerritoryMapping: Map<String, List<String>> = mapOf(
    "af" to listOf("NA", "ZA"),
    "agq" to listOf("CM"),
    "ak" to listOf("GH"),
    "am" to listOf("ET"),
    "ar" to listOf(
      "001", "AE", "BH", "DJ", "DZ", "EG", "EH", "ER", "IL", "IQ", "JO", "KM", "KW",
      "LB", "LY", "MA", "MR", "OM", "PS", "QA", "SA", "SD", "SO", "SS", "SY", "TD", "TN", "YE",
    ),
    "as" to listOf("IN"),
    "asa" to listOf("TZ"),
    "ast" to listOf("ES"),
    "az" to listOf("AZ", "AZ"),
    "bas" to listOf("CM"),
    "be" to listOf("BY"),
    "bem" to listOf("ZM"),
    "bez" to listOf("TZ"),
    "bg" to listOf("BG"),
    "bm" to listOf("ML"),
    "bn" to listOf("BD", "IN"),
    "bo" to listOf("CN", "IN"),
    "br" to listOf("FR"),
    "brx" to listOf("IN"),
    "bs" to listOf("BA", "BA"),
    "ca" to listOf("AD", "ES", "ES", "FR", "IT"),
    "ccp" to listOf("BD", "IN"),
    "ce" to listOf("RU"),
    "ceb" to listOf("PH"),
    "cgg" to listOf("UG"),
    "chr" to listOf("US"),
    "ckb" to listOf("IQ", "IR"),
    "cs" to listOf("CZ"),
    "cu" to listOf("RU"),
    "cy" to listOf("GB"),
    "da" to listOf("DK", "GL"),
    "dav" to listOf("KE"),
    "de" to listOf("AT", "BE", "CH", "DE", "IT", "LI", "LU"),
    "dje" to listOf("NE"),
    "dsb" to listOf("DE"),
    "dua" to listOf("CM"),
    "dyo" to listOf("SN"),
    "dz" to listOf("BT"),
    "ebu" to listOf("KE"),
    "ee" to listOf("GH", "TG"),
    "el" to listOf("CY", "GR"),
    "en" to listOf(
      "001", "150", "AE", "AG", "AI", "AS", "AT", "AU", "BB", "BE", "BI", "BM", "BS",
      "BW", "BZ", "CA", "CC", "CH", "CK", "CM", "CX", "CY", "DE", "DG", "DK", "DM", "ER", "FI",
      "FJ", "FK", "FM", "GB", "GD", "GG", "GH", "GI", "GM", "GU", "GY", "HK", "IE", "IL", "IM",
      "IN", "IO", "JE", "JM", "KE", "KI", "KN", "KY", "LC", "LR", "LS", "MG", "MH", "MO", "MP",
      "MS", "MT", "MU", "MW", "MY", "NA", "NF", "NG", "NL", "NR", "NU", "NZ", "PG", "PH", "PK",
      "PN", "PR", "PW", "RW", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SL", "SS", "SX", "SZ",
      "TC", "TK", "TO", "TT", "TV", "TZ", "UG", "UM", "US", "US", "VC", "VG", "VI", "VU", "WS",
      "ZA", "ZM", "ZW",
    ),
    "eo" to listOf("001"),
    "es" to listOf(
      "419", "AR", "BO", "BR", "BZ", "CL", "CO", "CR", "CU", "DO", "EA", "EC", "ES",
      "GQ", "GT", "HN", "IC", "MX", "NI", "PA", "PE", "PH", "PR", "PY", "SV", "US", "UY", "VE",
    ),
    "et" to listOf("EE"),
    "eu" to listOf("ES"),
    "ewo" to listOf("CM"),
    "fa" to listOf("AF", "IR"),
    "ff" to listOf(
      "BF", "CM", "GH", "GM", "GN", "GW", "LR", "MR", "NE", "NG", "SL", "SN", "BF", "CM",
      "GH", "GM", "GN", "GW", "LR", "MR", "NE", "NG", "SL", "SN",
    ),
    "fi" to listOf("FI"),
    "fil" to listOf("PH"),
    "fo" to listOf("DK", "FO"),
    "fr" to listOf(
      "BE", "BF", "BI", "BJ", "BL", "CA", "CD", "CF", "CG", "CH", "CI", "CM", "DJ", "DZ",
      "FR", "GA", "GF", "GN", "GP", "GQ", "HT", "KM", "LU", "MA", "MC", "MF", "MG", "ML", "MQ",
      "MR", "MU", "NC", "NE", "PF", "PM", "RE", "RW", "SC", "SN", "SY", "TD", "TG", "TN", "VU",
      "WF", "YT",
    ),
    "fur" to listOf("IT"),
    "fy" to listOf("NL"),
    "ga" to listOf("GB", "IE"),
    "gd" to listOf("GB"),
    "gl" to listOf("ES"),
    "gsw" to listOf("CH", "FR", "LI"),
    "gu" to listOf("IN"),
    "guz" to listOf("KE"),
    "gv" to listOf("IM"),
    "ha" to listOf("GH", "NE", "NG"),
    "haw" to listOf("US"),
    "he" to listOf("IL"),
    "hi" to listOf("IN"),
    "hr" to listOf("BA", "HR"),
    "hsb" to listOf("DE"),
    "hu" to listOf("HU"),
    "hy" to listOf("AM"),
    "ia" to listOf("001"),
    "id" to listOf("ID"),
    "ig" to listOf("NG"),
    "ii" to listOf("CN"),
    "is" to listOf("IS"),
    "it" to listOf("CH", "IT", "SM", "VA"),
    "ja" to listOf("JP"),
    "jgo" to listOf("CM"),
    "jmc" to listOf("TZ"),
    "jv" to listOf("ID"),
    "ka" to listOf("GE"),
    "kab" to listOf("DZ"),
    "kam" to listOf("KE"),
    "kde" to listOf("TZ"),
    "kea" to listOf("CV"),
    "khq" to listOf("ML"),
    "ki" to listOf("KE"),
    "kk" to listOf("KZ"),
    "kkj" to listOf("CM"),
    "kl" to listOf("GL"),
    "kln" to listOf("KE"),
    "km" to listOf("KH"),
    "kn" to listOf("IN"),
    "ko" to listOf("KP", "KR"),
    "kok" to listOf("IN"),
    "ks" to listOf("IN"),
    "ksb" to listOf("TZ"),
    "ksf" to listOf("CM"),
    "ksh" to listOf("DE"),
    "ku" to listOf("TR"),
    "kw" to listOf("GB"),
    "ky" to listOf("KG"),
    "lag" to listOf("TZ"),
    "lb" to listOf("LU"),
    "lg" to listOf("UG"),
    "lkt" to listOf("US"),
    "ln" to listOf("AO", "CD", "CF", "CG"),
    "lo" to listOf("LA"),
    "lrc" to listOf("IQ", "IR"),
    "lt" to listOf("LT"),
    "lu" to listOf("CD"),
    "luo" to listOf("KE"),
    "luy" to listOf("KE"),
    "lv" to listOf("LV"),
    "mai" to listOf("IN"),
    "mas" to listOf("KE", "TZ"),
    "mer" to listOf("KE"),
    "mfe" to listOf("MU"),
    "mg" to listOf("MG"),
    "mgh" to listOf("MZ"),
    "mgo" to listOf("CM"),
    "mi" to listOf("NZ"),
    "mk" to listOf("MK"),
    "ml" to listOf("IN"),
    "mn" to listOf("MN"),
    "mni" to listOf("IN"),
    "mr" to listOf("IN"),
    "ms" to listOf("BN", "ID", "MY", "SG"),
    "mt" to listOf("MT"),
    "mua" to listOf("CM"),
    "my" to listOf("MM"),
    "mzn" to listOf("IR"),
    "naq" to listOf("NA"),
    "nb" to listOf("NO", "SJ"),
    "nd" to listOf("ZW"),
    "nds" to listOf("DE", "NL"),
    "ne" to listOf("IN", "NP"),
    "nl" to listOf("AW", "BE", "BQ", "CW", "NL", "SR", "SX"),
    "nmg" to listOf("CM"),
    "nn" to listOf("NO"),
    "nnh" to listOf("CM"),
    "nus" to listOf("SS"),
    "nyn" to listOf("UG"),
    "om" to listOf("ET", "KE"),
    "or" to listOf("IN"),
    "os" to listOf("GE", "RU"),
    "pa" to listOf("PK", "IN"),
    "pcm" to listOf("NG"),
    "pl" to listOf("PL"),
    "prg" to listOf("001"),
    "ps" to listOf("AF", "PK"),
    "pt" to listOf("AO", "BR", "CH", "CV", "GQ", "GW", "LU", "MO", "MZ", "PT", "ST", "TL"),
    "qu" to listOf("BO", "EC", "PE"),
    "rm" to listOf("CH"),
    "rn" to listOf("BI"),
    "ro" to listOf("MD", "RO"),
    "rof" to listOf("TZ"),
    "ru" to listOf("BY", "KG", "KZ", "MD", "RU", "UA"),
    "rw" to listOf("RW"),
    "rwk" to listOf("TZ"),
    "sah" to listOf("RU"),
    "saq" to listOf("KE"),
    "sat" to listOf("IN"),
    "sbp" to listOf("TZ"),
    "sd" to listOf("PK", "IN"),
    "se" to listOf("FI", "NO", "SE"),
    "seh" to listOf("MZ"),
    "ses" to listOf("ML"),
    "sg" to listOf("CF"),
    "shi" to listOf("MA", "MA"),
    "si" to listOf("LK"),
    "sk" to listOf("SK"),
    "sl" to listOf("SI"),
    "smn" to listOf("FI"),
    "sn" to listOf("ZW"),
    "so" to listOf("DJ", "ET", "KE", "SO"),
    "sq" to listOf("AL", "MK", "XK"),
    "sr" to listOf("BA", "ME", "RS", "XK", "BA", "ME", "RS", "XK"),
    "su" to listOf("ID"),
    "sv" to listOf("AX", "FI", "SE"),
    "sw" to listOf("CD", "KE", "TZ", "UG"),
    "ta" to listOf("IN", "LK", "MY", "SG"),
    "te" to listOf("IN"),
    "teo" to listOf("KE", "UG"),
    "tg" to listOf("TJ"),
    "th" to listOf("TH"),
    "ti" to listOf("ER", "ET"),
    "tk" to listOf("TM"),
    "to" to listOf("TO"),
    "tr" to listOf("CY", "TR"),
    "tt" to listOf("RU"),
    "twq" to listOf("NE"),
    "tzm" to listOf("MA"),
    "ug" to listOf("CN"),
    "uk" to listOf("UA"),
    "ur" to listOf("IN", "PK"),
    "uz" to listOf("AF", "UZ", "UZ"),
    "vai" to listOf("LR", "LR"),
    "vi" to listOf("VN"),
    "vo" to listOf("001"),
    "vun" to listOf("TZ"),
    "wae" to listOf("CH"),
    "wo" to listOf("SN"),
    "xh" to listOf("ZA"),
    "xog" to listOf("UG"),
    "yav" to listOf("CM"),
    "yi" to listOf("001"),
    "yo" to listOf("BJ", "NG"),
    "yue" to listOf("CN", "HK"),
    "zgh" to listOf("MA"),
    "zh" to listOf("CN", "HK", "MO", "SG", "HK", "MO", "TW"),
    "zu" to listOf("ZA"),
  )

  fun isSpokenIn(languageCode: String, countryCode: String): Boolean =
    languageTerritoryMapping[languageCode]!!.contains(countryCode)
}
